services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"  
    environment:
      - PROFILE=prd
      - SPRING_DATA_MONGODB_URI=mongodb+srv://rafafiap:12345@cluster0.1ws5eqh.mongodb.net/lixo?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - C:/Users/BRibeirodefreitas/agenda-coleta-lixo:/app
    container_name: java_app
